repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"

docker:
  socket:
    path: "/var/run/docker.sock" # pks - /var/vcap/data/sys/run/docker/docker.sock

serviceAccount: "csp-sa"
server:
  serviceName: "csp-console-svc" # example
  port: 8080

image:
  repository: scanner
  tag: "4.6"
  pullPolicy: IfNotPresent

user:
password:
replicaCount: 1
livenessProbe: {}
readinessProbe: {}
resources: {}
  # Note: For recommendations please check the official sizing guide.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
