---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-svc
  labels:
    app: {{ .Release.Name }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.gate.service.type }}
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
  - port: {{ .Values.gate.service.externalPort }}
    targetPort: 3622
    protocol: TCP
    name: aqua-gate
  {{- if and (eq .Values.gate.service.type "NodePort") (.Values.gate.service.nodePort) }}
    nodePort: {{ .Values.gate.service.nodePort }}
  {{- end }}
  - port: {{ .Values.gate.grpcservice.externalPort }}
    targetPort: 8443
    protocol: TCP
    name: aqua-gate-ssl
  {{- if and (eq .Values.gate.service.type "NodePort") (.Values.gate.grpcservice.nodePort) }}
    nodePort: {{ .Values.gate.grpcservice.nodePort }}
  {{- end }}