---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-config
  namespace: {{ .Release.Namespace }}
data:
  SCALOCK_DBUSER: {{ .Values.db.external.enabled | ternary .Values.db.external.user "postgres" }}
  SCALOCK_DBNAME: {{ .Values.db.external.enabled | ternary .Values.db.external.name "scalock" }}
  {{- if .Values.db.external.enabled }}
  SCALOCK_DBHOST: {{ .Values.db.external.host }}
  {{- else }}
  SCALOCK_DBHOST: {{ .Release.Name }}-database-svc
  {{- end }}
  SCALOCK_DBPORT: {{ .Values.db.external.enabled | ternary .Values.db.external.port "5432" | quote }}
  SCALOCK_AUDIT_DBUSER: {{ .Values.db.external.enabled | ternary .Values.db.external.auditUser "postgres" }}
  SCALOCK_AUDIT_DBNAME: {{ .Values.db.external.enabled | ternary .Values.db.external.auditName "slk_audit" }}
  {{- if .Values.db.external.enabled }}
  SCALOCK_AUDIT_DBHOST: {{ .Values.db.external.auditHost }}
  {{- else }}
  SCALOCK_AUDIT_DBHOST: {{ .Release.Name }}-audit-database-svc
  {{- end }}
  SCALOCK_AUDIT_DBPORT: {{ .Values.db.external.enabled | ternary .Values.db.external.auditPort "5432" | quote }}
  {{- if .Values.activeactive }}
  AQUA_PUBSUB_DBUSER: {{ .Values.db.external.enabled | ternary .Values.db.external.pubsubUser "postgres" }}
  AQUA_PUBSUB_DBNAME: {{ .Values.db.external.enabled | ternary .Values.db.external.pubsubName "aqua_pubsub" }}
  {{- if .Values.db.external.enabled }}
  AQUA_PUBSUB_DBHOST: {{ .Values.db.external.pubsubHost }}
  {{- else }}
  AQUA_PUBSUB_DBHOST: {{ .Release.Name }}-database-svc
  {{- end }}
  AQUA_PUBSUB_DBPORT: {{ .Values.db.external.enabled | ternary .Values.db.external.pubsubPort "5432" | quote }}
  {{- end }}
  {{- if .Values.db.ssl }}
  SCALOCK_DBSSL: require
  {{- end }}
  {{- if .Values.db.auditssl }}
  SCALOCK_AUDIT_DBSSL: require
  {{- end }}
  {{- if .Values.db.pubsubssl }}
  AQUA_PUBSUB_DBSSL: require
  {{- end }}
  SCALOCK_LOG_LEVEL: {{ .Values.web.logLevel | default "INFO" }}
  {{- if .Values.clustermode }}
  CLUSTER_MODE: "enable"  
  {{- end }}
  {{- if .Values.activeactive }}
  AQUA_CLUSTER_MODE: "active-active"  
  {{- end }}
  {{- if .Values.web.maintenance_db.name }}
  AQUA_MAINTENANCE_DBNAME: {{ .Values.web.maintenance_db.name }}
  {{- end }}
  {{- if .Values.web.TLS.enabled }}
  AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"
  AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"
  {{- if .Values.web.TLS.rootCA_fileName }}
  AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"
  {{- end }}
  {{- end }}

