apiVersion: v1
name: aqua-quickstart
description: A Helm chart for Aqua CSP Quick Start
appVersion: "6.5"
version: "6.5.1"
icon: https://avatars3.githubusercontent.com/u/12783832?s=200&v=4
home: https://www.aquasec.com/
maintainers:
- name: Aqua Security, Inc.
  email: support@aquasec.com
