apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aqua-enforcer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aqua
  source:
    repoURL: 'https://helm.aquasec.com/'
    chart: enforcer
    targetRevision: 6.5.14
    helm:
      parameters:
        - name: gate.host
          value: aqua-lb
        - name: gate.port
          value: '443'
        - name: platform
          value: gke
        - name: image.tag
          value: 6.5.22110
  destination:
    server: 'https://34.91.104.18'
    namespace: aqua
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
