{{- if and ( .Values.serverSSL.enable ) ( .Values.serverSSL.createSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serverSSL.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  aqua-ssl.crt: {{ template "serverCertificate" . }}
{{- end }}