{{- if .Values.serverSSL.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serverSSL.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  server.crt: {{ template "serverCertificate" . }}
{{- end }}