---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kube-enforcer-config
  namespace: {{ .Release.Namespace }}
data:
  SCALOCK_LOG_LEVEL: "{{ .Values.logLevel | default "DEBUG" }}"
  AQUA_ENABLE_CACHE: "{{ .Values.aqua_enable_cache }}"
  AQUA_CACHE_EXPIRATION_PERIOD: "{{ .Values.aqua_cache_expiration_period | default "60"}}"
  AQUA_LOGICAL_NAME: "{{ .Values.logicalName }}"
  CLUSTER_NAME: "{{ .Values.clusterName }}"
  TLS_SERVER_CERT_FILEPATH: "/certs/server.crt"
  TLS_SERVER_KEY_FILEPATH: "/certs/server.key"
# mTLS env config
{{- if .Values.TLS.enabled }}
  AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"
  AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"
  AQUA_TLS_VERIFY: "{{ .Values.TLS.tls_verify | quote }}"
{{- if .Values.TLS.rootCA_fileName }}
  AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"
{{- end }}
{{- end }}
  AQUA_GATEWAY_SECURE_ADDRESS: {{ .Values.gateway.address | default "aqua-gateway-svc" }}:{{ .Values.gateway.port | default "8443" }}
  AQUA_KAP_ADD_ALL_CONTROL: "true"
  AQUA_WATCH_CONFIG_AUDIT_REPORT: "true"
{{- if .Values.kubeEnforcerAdvance.enable }}
  AQUA_TLS_PORT: "8449"
  AQUA_KE_SERVER_PORT: "8442"
  AQUA_ENVOY_MODE: "true"
{{- else }}
  AQUA_TLS_PORT: "8443"
{{- end }}
