---
# This role specific to kube-bench scans permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aqua-kube-enforcer
  namespace: aqua
rules:
  - apiGroups: ["*"]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["jobs"]
    verbs: ["create", "delete"]
{{- if eq .Values.platform "openshift" }}
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["create", "delete"]
{{- end }}