{{- if .Values.starboard.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
description: Used for Aqua Starboard to be scheduled with higher priority.
kind: PriorityClass
metadata:
  name: {{ template "starboardPriorityClass" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    aqua.component: starboard-operator
{{ include "aqua.labels" . | indent 4 }}
preemptionPolicy: {{ .Values.starboard.priorityClass.preemptionPolicy }}
value: {{ .Values.starboard.priorityClass.value }}
{{- end }}