apiVersion: v1
kind: Secret
metadata:
  name: trivy-operator-trivy-config
  namespace: aqua
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: kubectl