apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator
  namespace: aqua
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: kubectl
data:
  scanJob.podTemplateContainerSecurityContext: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true}"
  scanJob.compressLogs: "true"
  vulnerabilityReports.scanner: "Trivy"
  configAuditReports.scanner: "Trivy"
  report.recordFailedChecksOnly: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-policies-config
  namespace: aqua
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: aqua
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: kubectl