apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" . ) "secrets" }}
type: Opaque
data:
  USERNAME: {{ .Values.integration.username | toString | b64enc | quote }}
  PASSWORD: {{ .Values.integration.password | toString | b64enc | quote }}
  AQUA_KEY: {{ .Values.credentials.aqua_key | toString | b64enc | quote }}
  AQUA_SECRET: {{ .Values.credentials.aqua_secret | toString | b64enc | quote }}
  {{- if .Values.ssl.enabled }}
  {{- if .Values.ssl.ca }}
  ssl-ca-certificate: {{ .Values.ssl.ca | toString | b64enc }}
  {{- end }}
  ssl-certificate: {{ .Values.ssl.cert | toString | b64enc }}
  ssl-key: {{ .Values.ssl.key | toString | b64enc }}
  {{- end }}
