{{- if eq .Values.platform "openshift" }}

---
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    "helm.sh/hook": pre-install
    kubernetes.io/description: aqua cybcercenter scc provides all features of the
      restricted SCC but allows users to run with any root UID and access hostPath.
      This is must to run offline-cc in root user in container.
    release.openshift.io/create-only: "true"
  name: {{ .Release.Name }}-cc-scc
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Namespace }}-sa
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - hostPath

{{- end }}
